server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${whitea.datasource.driver-class-name}
    url: jdbc:mysql://${whitea.redis.host}:${whitea.datasource.port}/mybatis
    username: ${whitea.datasource.username}
    password: ${whitea.datasource.password}
  data:
    redis:
      database: ${whitea.redis.database}
      password: ${whitea.redis.password}
      port: ${whitea.redis.port}
      host: ${whitea.redis.host}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.whitea.sastpancake.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info
