server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${whitea.datasource.driver-class-name}
    url: jdbc:mysql://${whitea.redis.host}:${whitea.datasource.port}/${whitea.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${whitea.datasource.username}
    password: ${whitea.datasource.password}
    type: ${whitea.datasource.type}
  data:
    redis:
      database: ${whitea.redis.database}
      password: ${whitea.redis.password}
      port: ${whitea.redis.port}
      host: ${whitea.redis.host}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.whitea.sastpancake.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      whitea:
        sastpancake:
          mapper: warn
          service: warn
          controller: warn

whitea:
  jwt:
    # 管理端jwt令牌
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: whitea
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
